let books = [];

books[0] = 'https://www.goodreads.com/book/show/180748.Interviews_with_Francis_Bacon?from_search=true&from_srp=true&qid=BBWJ333EOi&rank=1';
books[1] = 'https://www.goodreads.com/book/show/578644.Billy_Liar?from_search=true&from_srp=true&qid=Q4LUsSKWWw&rank=1';
books[2] = 'https://www.goodreads.com/book/show/1775733.Room_at_the_Top?from_search=true&from_srp=true&qid=RWrGOaHKKJ&rank=1';
books[3] = 'https://www.goodreads.com/book/show/817501.On_Having_No_Head?from_search=true&from_srp=true&qid=PhTRxr96fv&rank=1';
books[4] = 'https://www.goodreads.com/book/show/75603.Kafka_Was_the_Rage?from_search=true&from_srp=true&qid=ryUnuVZq9c&rank=1';
books[5] = 'https://www.goodreads.com/book/show/41817486-a-clockwork-orange?from_search=true&from_srp=true&qid=XQCSBPy98m&rank=1';
books[6] = 'https://www.goodreads.com/book/show/109713.City_of_Night';
books[7] = 'https://www.goodreads.com/book/show/297673.The_Brief_Wondrous_Life_of_Oscar_Wao?ac=1&from_search=true&qid=h7vXqgz4Gc&rank=1';
books[8] = 'https://www.goodreads.com/book/show/2175.Madame_Bovary?ac=1&from_search=true&qid=ywB6f8mCrA&rank=1';
books[9] = 'https://www.goodreads.com/book/show/1371.The_Iliad?ac=1&from_search=true&qid=pSutKIVthZ&rank=1';
books[10] = 'https://www.goodreads.com/book/show/77013.As_I_Lay_Dying?ac=1&from_search=true&qid=iRME7FYQzM&rank=1';
books[11] = 'https://www.goodreads.com/book/show/2127256.The_Complete_Tadanori_Yokoo?from_search=true&from_srp=true&qid=bztovCOp4N&rank=1';
books[12] = 'https://www.goodreads.com/book/show/243381.Berlin_Alexanderplatz?from_search=true&from_srp=true&qid=OIvWcjZdSP&rank=1';
books[13] = 'https://www.goodreads.com/book/show/1553589.Inside_the_Whale_and_Other_Essays?ac=1&from_search=true&qid=jHQFZOPNQT&rank=1';
books[14] = 'https://www.goodreads.com/book/show/705163.Mr_Norris_Changes_Trains?ac=1&from_search=true&qid=UzmzpsWBKX&rank=1';
books[15] = 'https://www.goodreads.com/book/show/188878.Dictionary_of_Subjects_and_Symbols_in_Art?ac=1&from_search=true&qid=ZtOQ3VIusx&rank=1';
books[16] = 'https://www.goodreads.com/book/show/2346043.David_Bomberg?ac=1&from_search=true&qid=gF5tPJjWEd&rank=1';
books[17] = 'https://www.goodreads.com/book/show/256324.Blast_1?ac=1&from_search=true&qid=fPEQ0P1gu7&rank=1';
books[18] = 'https://www.goodreads.com/book/show/349929.Passing?ac=1&from_search=true&qid=ERW7PmPIbh&rank=1';
books[19] = 'https://www.goodreads.com/book/show/189630.Beyond_the_Brillo_Box?ac=1&from_search=true&qid=YHqjemCCzn&rank=1';
books[20] = 'https://www.goodreads.com/book/show/22478.The_Origin_of_Consciousness_in_the_Breakdown_of_the_Bicameral_Mind?ac=1&from_search=true&qid=R3zSusYj01&rank=1';
books[21] = 'https://www.goodreads.com/book/show/50535.In_Bluebeard_s_Castle?from_search=true&from_srp=true&qid=wjZNBBtiJT&rank=1';
books[22] = 'https://www.goodreads.com/book/show/67729.Hawksmoor?ac=1&from_search=true&qid=MbnEu0nayF&rank=1';
books[23] = 'https://www.goodreads.com/book/show/496585.The_Divided_Self?ac=1&from_search=true&qid=3TpDttXnbu&rank=1';
books[24] = 'https://www.goodreads.com/book/show/49552.The_Stranger?ac=1&from_search=true&qid=CkaWZ9i59a&rank=1';
books[25] = 'https://www.goodreads.com/book/show/868448.Infants_of_the_Spring?ac=1&from_search=true&qid=N9zb6dgdPa&rank=1';
books[26] = 'https://www.goodreads.com/book/show/153479.The_Quest_for_Christa_T_?ac=1&from_search=true&qid=K7a6R6zV1d&rank=1';
books[27] = 'https://www.goodreads.com/book/show/76844.The_Songlines?ac=1&from_search=true&qid=VPqdOOnW6J&rank=1';
books[28] = 'https://www.goodreads.com/book/show/653651.Nights_at_the_Circus?ac=1&from_search=true&qid=bYlhbyNWPq&rank=1';
books[29] = 'https://www.goodreads.com/book/show/117833.The_Master_and_Margarita?ac=1&from_search=true&qid=0j2FQpjDer&rank=1';
books[30] = 'https://www.goodreads.com/book/show/517188.The_Prime_of_Miss_Jean_Brodie?ac=1&from_search=true&qid=iihy7EZg5L&rank=1';
books[31] = 'https://www.goodreads.com/book/show/7604.Lolita?ac=1&from_search=true&qid=xSEJmsIcKC&rank=1';
books[32] = 'https://www.goodreads.com/book/show/6551.Herzog?ac=1&from_search=true&qid=hyeJJT8nJE&rank=1';
books[33] = 'https://www.goodreads.com/book/show/887348.Puckoon?ac=1&from_search=true&qid=VxoYXauPMA&rank=1';
books[34] = 'https://www.goodreads.com/book/show/228630.Black_Boy?from_search=true&from_srp=true&qid=jxjRjHLmu2&rank=1';
books[35] = 'https://www.goodreads.com/book/show/4671.The_Great_Gatsby?from_search=true&from_srp=true&qid=HLggLVIFWy&rank=1';
books[36] = 'https://www.goodreads.com/book/show/162332.The_Sailor_Who_Fell_from_Grace_with_the_Sea?ac=1&from_search=true&qid=qdWlDCzEhM&rank=1';
books[37] = 'https://www.goodreads.com/book/show/30672.Darkness_at_Noon?ac=1&from_search=true&qid=EHVdPXWiPg&rank=1';
books[38] = 'https://www.goodreads.com/book/show/34080.The_Waste_Land?ac=1&from_search=true&qid=iy3Tdzw3ls&rank=2';
books[39] = 'https://www.goodreads.com/book/show/168655.McTeague?ac=1&from_search=true&qid=69aNmuJTbb&rank=1';
books[40] = 'https://www.goodreads.com/book/show/18825.Money?ac=1&from_search=true&qid=VpBilsO7O3&rank=1';
books[41] = 'https://www.goodreads.com/book/show/67880.The_Outsider?ac=1&from_search=true&qid=CbWTXSekCe&rank=5';
books[42] = 'https://www.goodreads.com/book/show/1412860.Strange_People?ac=1&from_search=true&qid=upm6n9ji6s&rank=2';
books[43] = 'https://www.goodreads.com/book/show/938052.English_Journey?ac=1&from_search=true&qid=u3uPnbAPAu&rank=2';
books[44] = 'https://www.goodreads.com/book/show/310612.A_Confederacy_of_Dunces?ac=1&from_search=true&qid=ciFXYA00HQ&rank=1';
books[45] = 'https://www.goodreads.com/book/show/113441.The_Day_of_the_Locust?ac=1&from_search=true&qid=GQEJjXDxSj&rank=1';
books[46] = 'https://www.goodreads.com/book/show/40961427-1984?ac=1&from_search=true&qid=lfxya4jaYJ&rank=1';
books[47] = 'https://www.goodreads.com/book/show/876172.The_Life_and_Times_of_Little_Richard?ac=1&from_search=true&qid=6K2IwhehI6&rank=1';
books[48] = 'https://www.goodreads.com/book/show/386673.Awopbopaloobop_Alopbamboom?ac=1&from_search=true&qid=A6MEHnYR7d&rank=1';
books[49] = 'https://www.goodreads.com/book/show/574925.Mystery_Train?ac=1&from_search=true&qid=sVvkp5Ulpp&rank=1';
books[50] = 'https://www.goodreads.com/book/show/26074463-the-beano-annual-2015?from_search=true&from_srp=true&qid=YDsTPrWyXF&rank=1';
books[51] = 'https://www.goodreads.com/book/show/395111.Read_Yourself_Raw';
books[52] = 'https://www.goodreads.com/book/show/28251250-white-noise?ac=1&from_search=true&qid=eiiBG2CqsR&rank=1';
books[53] = 'https://www.goodreads.com/book/show/890216.Sweet_Soul_Music?ac=1&from_search=true&qid=cuZV1j4AOD&rank=1';
books[54] = 'https://www.goodreads.com/book/show/765651.Silence?ac=1&from_search=true&qid=odJFelQQYY&rank=1';
books[55] = 'https://www.goodreads.com/book/show/235785.Writers_at_Work?ac=1&from_search=true&qid=fh1YaLA9lr&rank=1';
books[56] = 'https://www.goodreads.com/book/show/1088969.The_Sound_of_the_City?ac=1&from_search=true&qid=6QRKRxhGxH&rank=1';
books[57] = 'https://www.goodreads.com/book/show/2638519-octobriana-and-the-russian-underground?ac=1&from_search=true&qid=n6MA3esey6&rank=1';
books[58] = 'https://www.goodreads.com/book/show/186926.The_Street?ac=1&from_search=true&qid=TM5SsIZksx&rank=2';
books[59] = 'https://www.goodreads.com/book/show/16707.Wonder_Boys?ac=1&from_search=true&qid=chpmuyfTxw&rank=1';
books[60] = 'https://www.goodreads.com/book/show/50275.Last_Exit_to_Brooklyn?ac=1&from_search=true&qid=dhyIxLNUxO&rank=1';
books[61] = 'https://www.goodreads.com/book/show/2767.A_People_s_History_of_the_United_States?ac=1&from_search=true&qid=mpmOfWBAJB&rank=1';
books[62] = 'https://www.goodreads.com/book/show/1822711.The_Age_of_American_Unreason?ac=1&from_search=true&qid=FY96gYBswd&rank=1';
books[63] = 'https://www.goodreads.com/book/show/927916.Metropolitan_Life?ac=1&from_search=true&qid=EpNWuy8ocE&rank=1';
books[64] = 'https://www.goodreads.com/book/show/17904.The_Coast_of_Utopia?ac=1&from_search=true&qid=YHuXVzaEsR&rank=1';
books[65] = 'https://www.goodreads.com/book/show/75495.The_Bridge?ac=1&from_search=true&qid=PgNhwDmHuM&rank=1';
books[66] = 'https://www.goodreads.com/book/show/18589836-all-the-emperor-s-horses?ac=1&from_search=true&qid=WQiZMTpmuC&rank=1';
books[67] = 'https://www.goodreads.com/book/show/8913370-fingersmith?ac=1&from_search=true&qid=WBtyKA1cgs&rank=1';
books[68] = 'https://www.goodreads.com/book/show/8822.Earthly_Powers?ac=1&from_search=true&qid=XoI5vYODAw&rank=1';
books[69] = 'https://www.goodreads.com/book/show/7101.The_42nd_Parallel?ac=1&from_search=true&qid=NfYI67tgFx&rank=1';
books[70] = 'https://www.goodreads.com/book/show/50386.Tales_of_Beatnik_Glory?ac=1&from_search=true&qid=IyoBCM7Hte&rank=1';
books[71] = 'https://www.goodreads.com/book/show/883420.The_Bird_Artist?ac=1&from_search=true&qid=1SvWBuwVba&rank=1';
books[72] = 'https://www.goodreads.com/book/show/687352.Nowhere_to_Run?ac=1&from_search=true&qid=zTMYNur2Hu&rank=1';
books[73] = 'https://www.goodreads.com/book/show/400379.Before_the_Deluge?ac=1&from_search=true&qid=T3PYPwcxN7&rank=1';
books[74] = 'https://www.goodreads.com/book/show/101157.Sexual_Personae?ac=1&from_search=true&qid=MkSy8ARf6s&rank=1';
books[75] = 'https://www.goodreads.com/book/show/372809.The_American_Way_of_Death_Revisited?ac=1&from_search=true&qid=P1EVC06o9j&rank=1';
books[76] = 'https://www.goodreads.com/book/show/168642.In_Cold_Blood?ac=1&from_search=true&qid=MwTbNPmm4O&rank=1';
books[77] = 'https://www.goodreads.com/book/show/32049.Lady_Chatterley_s_Lover?ac=1&from_search=true&qid=ADRro7SzqC&rank=1';
books[78] = 'https://www.goodreads.com/book/show/652609.Teenage?ac=1&from_search=true&qid=hpeDT0JrXR&rank=1';
books[79] = 'https://www.goodreads.com/book/show/142492.Vile_Bodies?ac=1&from_search=true&qid=hRYkP5McLN&rank=1';
books[80] = 'https://www.goodreads.com/book/show/3730.The_Hidden_Persuaders?ac=1&from_search=true&qid=gmHEIWpW7q&rank=1';
books[81] = 'https://www.goodreads.com/book/show/464260.The_Fire_Next_Time?ac=1&from_search=true&qid=Qofwp9aByR&rank=1';
books[82] = 'https://www.goodreads.com/book/show/1685689.VIZ_Comic_The_Big_Hard_One';
books[83] = 'https://www.goodreads.com/book/show/12708744-private-eye-the-first-50-years';
books[84] = 'https://www.goodreads.com/book/show/1136201.Selected_Poems?ac=1&from_search=true&qid=bpKtM7t5eg&rank=1';
books[85] = 'https://www.goodreads.com/book/show/43377.The_Trial_of_Henry_Kissinger?ac=1&from_search=true&qid=TNDU3s7ySI&rank=1';
books[86] = 'https://www.goodreads.com/book/show/2176.Flaubert_s_Parrot?ac=1&from_search=true&qid=Lv7ttWu8PF&rank=1';
books[87] = 'https://www.goodreads.com/book/show/157687.Maldoror_and_the_Complete_Works?ac=1&from_search=true&qid=p48fLYmh33&rank=1';
books[88] = 'https://www.goodreads.com/book/show/70401.On_the_Road?ac=1&from_search=true&qid=raE1bWISF6&rank=1';
books[89] = 'https://www.goodreads.com/book/show/14315.Mr_Wilson_s_Cabinet_Of_Wonder?ac=1&from_search=true&qid=iCrtw8VF7h&rank=1';
books[90] = 'https://www.goodreads.com/book/show/420474.Zanoni?ac=1&from_search=true&qid=Xvd7tAt9et&rank=1';
books[91] = 'https://www.goodreads.com/book/show/302614.Transcendental_Magic?ac=1&from_search=true&qid=FOLtKFgBTX&rank=1';
books[92] = 'https://www.goodreads.com/book/show/110763.The_Gnostic_Gospels?ac=1&from_search=true&qid=0Kb06bEpHP&rank=1';
books[93] = 'https://www.goodreads.com/book/show/625094.The_Leopard?ac=1&from_search=true&qid=lY83lLmGtP&rank=3';
books[94] = 'https://www.goodreads.com/book/show/15645.Inferno?ac=1&from_search=true&qid=fyCm1Okeb4&rank=4';
books[95] = 'https://www.goodreads.com/book/show/18589844-a-grave-for-a-dolphin?ac=1&from_search=true&qid=wb60rAvMCt&rank=1';
books[96] = 'https://www.goodreads.com/book/show/285810.The_Insult?ac=1&from_search=true&qid=SoKLd3Com8&rank=3';
books[97] = 'https://www.goodreads.com/book/show/6873.In_Between_the_Sheets?ac=1&from_search=true&qid=P2q15BMqFO&rank=1';
books[98] = 'https://www.goodreads.com/book/show/38155.A_People_s_Tragedy?ac=1&from_search=true&qid=hegU9YVWc7&rank=1';
books[99] = 'https://www.goodreads.com/book/show/71149.Journey_into_the_Whirlwind?ac=1&from_search=true&qid=i3wP2XWRKx&rank=1';


function randomNumber(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min) + min);
}

let randomBook = books[randomNumber(0, 100)];

document.querySelector('a').setAttribute('href', randomBook);